// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Password  string           `json:"password"`
	Currency  string           `json:"currency"`
	Balance   pgtype.Numeric   `json:"balance"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type Transaction struct {
	ID         pgtype.UUID      `json:"id"`
	SenderID   pgtype.UUID      `json:"sender_id"`
	ReceiverID pgtype.UUID      `json:"receiver_id"`
	Amount     string           `json:"amount"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}
